BATCH_SIZE = 32
LR = 1e-8
WEIGHT_DECAY = 1e-1
EPOCHS = 1000
DEVICE = None

GRAD_CLIP = False
GRAD_CLIP_MAX_NORM = 0.5

USE_LHS_EMBEDDING = True
LHS_EMBEDDING_DIM = 128
UNIQUE_ATOMS = 100
UNIQUE_CHARGES = 15
UNIQUE_BONDS = 20
MPNN_FEATURES_DIM = (2 * LHS_EMBEDDING_DIM) if USE_LHS_EMBEDDING else 2

USE_TRANS_ENCODER = False

VOCAB_SIZE = None
RHS_EMBEDDING_DIM = 256
NUM_HEADS = 8
NUM_DECODER_LAYERS = 4

LOAD_MODEL_PATH = 'models/model.pt'
SAVE_MODEL_PATH = 'models/model.pt'
