BATCH_SIZE = 32
LR = 0.00001
WEIGHT_DECAY = 0.0001
EPOCHS = 1000
DEVICE = None

VOCAB_SIZE = None
EMBEDDING_DIM = 256
NUM_HEADS = 8
NUM_DECODER_LAYERS = 4

LOAD_MODEL_PATH = 'models/model.pt'
SAVE_MODEL_PATH = 'models/model.pt'
